import Link from "next/link";
import { createAdminClient } from "@/lib/supabase";
import { Header } from "@/components/layout/header";
import { formatPercent } from "@/lib/utils";
import { getCommunitySignalReport, type BreakdownRow } from "@/lib/queries/community-report";
import { COMMUNITY_STRATEGY_ID } from "./constants";

export const revalidate = 0;

function BreakdownTable({
  title,
  rows,
}: {
  title: string;
  rows: BreakdownRow[];
}) {
  return (
    <div className="flex-1 min-w-0">
      <p
        className="text-[10px] tracking-widest uppercase px-6 py-4 border-b"
        style={{ color: "var(--muted-foreground)", borderColor: "var(--border)" }}
      >
        {title}
      </p>
      {rows.length === 0 ? (
        <p className="px-6 py-8 text-sm" style={{ color: "var(--muted-foreground)" }}>
          Not enough resolved signals yet.
        </p>
      ) : (
        <table className="w-full text-xs">
          <thead>
            <tr style={{ borderBottom: "1px solid var(--border)" }}>
              {["", "Signals", "Win Rate", "Avg Pips"].map((c) => (
                <th
                  key={c}
                  className="text-left px-6 py-2.5 font-medium tracking-wider uppercase text-[10px]"
                  style={{ color: "var(--muted-foreground)" }}
                >
                  {c}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((r) => (
              <tr
                key={r.label}
                className="hover:bg-accent transition-colors"
                style={{ borderBottom: "1px solid var(--border)" }}
              >
                <td className="px-6 py-3 font-semibold capitalize" style={{ color: "var(--foreground)" }}>
                  {r.label}
                </td>
                <td className="px-6 py-3 metric-number" style={{ color: "var(--muted-foreground)" }}>
                  {r.signals}
                </td>
                <td
                  className="px-6 py-3 metric-number"
                  style={{
                    color:
                      r.winRate === null
                        ? "var(--muted-foreground)"
                        : r.winRate >= 50
                          ? "var(--success)"
                          : "var(--destructive)",
                  }}
                >
                  {r.winRate !== null ? formatPercent(r.winRate) : "—"}
                </td>
                <td className="px-6 py-3 metric-number" style={{ color: "var(--muted-foreground)" }}>
                  {r.avgPips !== null ? r.avgPips.toFixed(1) : "—"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}

export default async function CommunitySignalReportPage() {
  const supabase = createAdminClient();
  const report = await getCommunitySignalReport(supabase, 90);

  return (
    <>
      <Header title="Community Signals — Improvement Report" />
      <div className="flex-1 overflow-auto">
        <div className="max-w-5xl mx-auto px-6 py-8 space-y-8">
          <div className="flex items-center justify-between">
            <p className="text-xs" style={{ color: "var(--muted-foreground)" }}>
              Resolved community signals, last {report.windowDays} days — generated by{" "}
              <Link
                href={`/strategies/${COMMUNITY_STRATEGY_ID}/tuning`}
                className="hover:underline"
                style={{ color: "var(--primary)" }}
              >
                {COMMUNITY_STRATEGY_ID}
              </Link>
              . Uses cron-resolved outcomes, not self-reported journaling.
            </p>
            <Link href="/signals" className="text-xs hover:underline" style={{ color: "var(--primary)" }}>
              ← Back to Signals
            </Link>
          </div>

          {/* Overall stats strip */}
          <div
            className="grid grid-cols-3 divide-x border rounded-lg overflow-hidden"
            style={{ borderColor: "var(--border)" }}
          >
            {(
              [
                ["Resolved Signals", report.totalClosed],
                [
                  "Overall Win Rate",
                  report.overallWinRate !== null ? formatPercent(report.overallWinRate) : "—",
                ],
                [
                  "Overall Avg Pips",
                  report.overallAvgPips !== null ? report.overallAvgPips.toFixed(1) : "—",
                ],
              ] as [string, string | number][]
            ).map(([label, value]) => (
              <div key={label} className="px-6 py-4">
                <p
                  className="text-[10px] tracking-widest uppercase mb-1"
                  style={{ color: "var(--muted-foreground)" }}
                >
                  {label}
                </p>
                <p className="text-xl font-bold metric-number" style={{ color: "var(--foreground)" }}>
                  {value}
                </p>
              </div>
            ))}
          </div>

          <div className="flex divide-x border rounded-lg overflow-hidden" style={{ borderColor: "var(--border)" }}>
            <BreakdownTable title="By Confidence Bucket" rows={report.byConfidence} />
            <BreakdownTable title="By Direction" rows={report.byDirection} />
          </div>

          <div className="flex divide-x border rounded-lg overflow-hidden" style={{ borderColor: "var(--border)" }}>
            <BreakdownTable title="By Day of Week" rows={report.byDayOfWeek} />
            <BreakdownTable title="By Session" rows={report.bySession} />
          </div>
        </div>
      </div>
    </>
  );
}
